import { PortfolioReleasePayload } from "../types/portfolio";

export const DEFAULT_PORTFOLIO_CONFIG: PortfolioReleasePayload = {
  site_config: {
    full_name: "Pitambar Panda",
    display_name: "Raj",
    hero_intro: "HELLO, I'M",
    hero_metadata: "VSSUT CSE · ODISHA, INDIA · 2026",
    hero_quote: "I BUILD TO UNDERSTAND. I ENGINEER TO CREATE.",
    hero_kinetic_words: ["INTELLIGENT", "AUTONOMOUS", "SYSTEMS", "SOFTWARE"],
    about_headline: "I learn by building.",
    about_paragraphs: [
      "I started by breaking down physics and mechanics from first principles—teaching conceptual science and understanding how complex systems operate.",
      "Now in Computer Science at VSSUT Burla, I apply that same first-principles engineering to local-first AI, persistent memory engines, water intelligence systems, and autonomous software.",
      "I don't wait for permission or follow tutorials. I design architectures, run tests, and ship software that solves real technical problems.",
    ],
    about_tags: [
      "AI & COGNITIVE SYSTEMS",
      "PERSISTENT MEMORY",
      "ROBOTICS & EMBEDDED",
      "FIRST-PRINCIPLES LEARNING",
    ],
    contact_email: "theraj.wav@gmail.com",
    contact_headline: "LET'S BUILD SOMETHING INTERESTING.",
    contact_subtext:
      "I'm always interested in ideas worth exploring, systems worth understanding, and things worth building.",
    location_text: "VSSUT BURLA · ODISHA, INDIA",
    colophon_text: "PITAMBAR PANDA / RAJ · © 2026 · INNOSPHERE",
    resume_url: "/resume.pdf",
    section_visibility: {
      hero: true,
      about: true,
      lab: true,
      path: true,
      work: true,
      tech: true,
      contact: true,
    },
  },
  projects: [
    {
      slug: "raj-os",
      name: "RAJ Assistant / RAJ OS",
      category: "LOCAL-FIRST AI SYSTEM",
      badge: "WORKING CORE",
      tagline:
        "Personal AI designed around persistent memory, cognitive intent routing, and permission-controlled local execution.",
      systems_specs: [
        "▸ Memory: SQLite WAL Mode & FTS5 Document Brain",
        "▸ Routing: Multi-tier Cognitive Intent Engine",
        "▸ Security: 5-Tier Permission Rings Architecture",
        "▸ Models: Multi-LLM Gateway (Cloud & Local)",
      ],
      tech_stack_summary: "Python 3.11+ · SQLite · Multi-LLM · FTS5 · macOS/Linux",
      github_url: "https://github.com/rajwav/raj-assistant",
      live_url: null,
      image_url: "/images/projects/01-raj-os.svg",
      display_order: 1,
      is_enabled: true,
    },
    {
      slug: "aquaneon",
      name: "AquaNeon",
      category: "AI WATER INTELLIGENCE",
      badge: "LIVE PLATFORM",
      tagline:
        "Telemetry ingestion, multivariate anomaly detection, TreeSHAP feature attributions, and digital-twin SCADA simulation.",
      systems_specs: [
        "▸ Detection: Isolation Forest & Balanced Random Forest",
        "▸ Explainability: TreeSHAP Feature Attributions",
        "▸ Forecasting: HistGradientBoosting 24h Telemetry",
        "▸ Simulation: SCADA Actuator Digital Twin Engine",
      ],
      tech_stack_summary: "FastAPI · TreeSHAP · Scikit-Learn · Streamlit · Render",
      github_url: "https://github.com/rajwav/neon_water_project",
      live_url: "https://autonex-aqua-neon.onrender.com/",
      image_url: "/images/projects/02-aquaneon.svg",
      display_order: 2,
      is_enabled: true,
    },
    {
      slug: "tara",
      name: "TARA",
      category: "PERSONAL AI ARCHITECTURE",
      badge: "ARCHITECTURE EXPERIMENT",
      tagline:
        "Lightweight personal AI architecture engineered in Python for Apple Silicon with safe macOS system actions.",
      systems_specs: [
        "▸ Inference: Single-Request LLM Streaming",
        "▸ Brain: Groq API with Local Ollama Fallback",
        "▸ Memory: Non-destructive Episodic Fact Extraction",
        "▸ Gateway: Audited macOS Action Execution & Audio VAD",
      ],
      tech_stack_summary: "Python · Groq · Ollama · SQLite · Audio VAD · Apple Silicon",
      github_url: "https://github.com/rajwav/TARA",
      live_url: null,
      image_url: "/images/projects/03-tara.svg",
      display_order: 3,
      is_enabled: true,
    },
    {
      slug: "samvad",
      name: "Samvad",
      category: "REAL-TIME SOFTWARE",
      badge: "WEB PROTOTYPE",
      tagline:
        "Real-time communication and collaborative workspace engineered with modern web standards and responsive architecture.",
      systems_specs: [
        "▸ Framework: Next.js 16 App Router & React 19",
        "▸ Workspace: Low-Latency Dialogue & Collaboration",
        "▸ Design: Modular Component Architecture",
      ],
      tech_stack_summary: "Next.js 16 · React 19 · TypeScript · Responsive CSS",
      github_url: "https://github.com/rajwav/samvad",
      live_url: null,
      image_url: "/images/projects/04-samvad.svg",
      display_order: 4,
      is_enabled: true,
    },
    {
      slug: "the-lab",
      name: "THE LAB",
      category: "EXPERIMENTS & PROTOTYPES",
      badge: "EXPLORATORY WORK",
      tagline:
        "A continuous digital laboratory for ongoing experiments, sensor telemetry, edge AI, and hardware-software fusion.",
      systems_specs: [
        "▸ Prototypes: Sensor Fusion & Edge Computing Models",
        "▸ Explorations: Autonomous Agent Orchestration",
        "▸ Inquiry: Computational Physics & Interactive Tools",
      ],
      tech_stack_summary: "C++ · Python · Edge Telemetry · Micro-controllers · Linux",
      github_url: "https://github.com/rajwav/rajwav",
      live_url: null,
      image_url: "/images/projects/05-the-lab.svg",
      display_order: 5,
      is_enabled: true,
    },
    {
      slug: "innosphere",
      name: "INNOSPHERE",
      category: "LONG-TERM VISION",
      badge: "DEEP-TECH DIRECTION",
      tagline:
        "Long-term deep-tech direction exploring autonomous robotics, edge intelligence, and physical-world computing.",
      systems_specs: [
        "▸ Domain: Autonomous Robotics & Edge Intelligence",
        "▸ Focus: Physical Computing & Distributed Telemetry",
        "▸ Method: First-Principles Engineering & Continuous Shipping",
      ],
      tech_stack_summary: "Autonomous Systems · Robotics · Deep Tech · AI Infrastructure",
      github_url: "https://github.com/rajwav",
      live_url: null,
      image_url: "/images/projects/06-innosphere.svg",
      display_order: 6,
      is_enabled: true,
    },
  ],
  tech_stack: [
    {
      tech_slug: "python",
      display_name: "PYTHON 3.11+",
      decal_url: "/images/tech/python.svg",
      display_order: 1,
      is_enabled: true,
    },
    {
      tech_slug: "pytorch",
      display_name: "PYTORCH",
      decal_url: "/images/tech/pytorch.svg",
      display_order: 2,
      is_enabled: true,
    },
    {
      tech_slug: "fastapi",
      display_name: "FASTAPI",
      decal_url: "/images/tech/fastapi.svg",
      display_order: 3,
      is_enabled: true,
    },
    {
      tech_slug: "sqlite",
      display_name: "SQLITE WAL",
      decal_url: "/images/tech/sqlite.svg",
      display_order: 4,
      is_enabled: true,
    },
    {
      tech_slug: "cpp",
      display_name: "C++",
      decal_url: "/images/tech/cpp.svg",
      display_order: 5,
      is_enabled: true,
    },
    {
      tech_slug: "docker",
      display_name: "DOCKER",
      decal_url: "/images/tech/docker.svg",
      display_order: 6,
      is_enabled: true,
    },
    {
      tech_slug: "linux",
      display_name: "LINUX",
      decal_url: "/images/tech/linux.svg",
      display_order: 7,
      is_enabled: true,
    },
    {
      tech_slug: "react",
      display_name: "REACT 19",
      decal_url: "/images/tech/react.svg",
      display_order: 8,
      is_enabled: true,
    },
  ],
  lab_modules: [
    {
      module_code: "01 // THINK",
      module_status: "[SYS_MOD // 01 · ACTIVE]",
      subtitle: "AI · REASONING · TELEMETRY",
      specs: [
        "Local-First AI & Neural Models",
        "Cognitive Routing & Multi-LLM",
        "Persistent Memory & SQLite WAL",
        "Explainable ML & TreeSHAP",
        "Telemetry Intelligence & SCADA",
        "First-Principles Systems Thinking",
      ],
      toolchain: [
        "Python",
        "FastAPI",
        "PyTorch",
        "Scikit-Learn",
        "SQLite WAL",
        "TreeSHAP",
        "Ollama",
        "Linux",
      ],
      display_order: 1,
      is_enabled: true,
    },
    {
      module_code: "02 // BUILD",
      module_status: "[SYS_MOD // 02 · ACTIVE]",
      subtitle: "SOFTWARE · INTERFACES · COMPUTING",
      specs: [
        "Full-Stack Systems Architecture",
        "Real-Time Collaboration Engines",
        "Interactive 3D & WebGL/Three.js",
        "High-Concurrency & REST APIs",
        "Human-Computer Interaction (HCI)",
        "Experimental Software & Tooling",
      ],
      toolchain: [
        "TypeScript",
        "React 19",
        "Next.js 16",
        "Three.js",
        "GSAP",
        "C++",
        "REST APIs",
        "Docker",
      ],
      display_order: 2,
      is_enabled: true,
    },
  ],
  path_milestones: [
    {
      year: "2021",
      title: "TEACHING & EXPLORATION",
      organization: "bPITAMBAR · Conceptual Learning",
      description:
        "Began deconstructing and teaching physics and conceptual science from first principles. Built deep foundational curiosity for how physical systems, forces, and mathematical abstractions operate in the real world.",
      context_chip: "FIRST PRINCIPLES",
      display_order: 1,
      is_enabled: true,
    },
    {
      year: "2024",
      title: "COMPUTER SCIENCE",
      organization: "VSSUT Burla · B.Tech CSE",
      description:
        "Started formal Computer Science Engineering at Veer Surendra Sai University of Technology. Began translating mathematical models and physics intuition directly into code, algorithms, and software architectures.",
      context_chip: "FOUNDATION",
      display_order: 2,
      is_enabled: true,
    },
    {
      year: "2026",
      title: "BUILDING & EXPERIMENTING",
      organization: "Active Systems Builder · Ongoing Exploration",
      description:
        "Architecting real systems: building local-first AI runtimes (RAJ OS), water telemetry intelligence (AquaNeon), collaborative platforms (Samvad), and exploratory embedded experiments in the lab.",
      context_chip: "CURRENT FOCUS",
      display_order: 3,
      is_enabled: true,
    },
  ],
  social_links: [
    {
      platform_slug: "github",
      label: "GITHUB",
      handle: "@rajwav",
      action_text: "VIEW PROFILE ↗",
      url: "https://github.com/rajwav",
      display_order: 1,
      is_enabled: true,
    },
    {
      platform_slug: "linkedin",
      label: "LINKEDIN",
      handle: "PITAMBAR PANDA",
      action_text: "CONNECT ↗",
      url: "https://www.linkedin.com/in/pitambar-panda-0001braj/",
      display_order: 2,
      is_enabled: true,
    },
    {
      platform_slug: "youtube",
      label: "YOUTUBE",
      handle: "TRW — RAJ",
      action_text: "WATCH ↗",
      url: "https://www.youtube.com/@trw-raj",
      display_order: 3,
      is_enabled: true,
    },
    {
      platform_slug: "instagram",
      label: "INSTAGRAM",
      handle: "@pitambar_28",
      action_text: "VIEW ↗",
      url: "https://www.instagram.com/pitambar_28/",
      display_order: 4,
      is_enabled: true,
    },
  ],
  published_at: "2026-08-28T00:00:00.000Z",
  version: 1,
};
